import { tmpdir } from "node:os";
import { mkdtemp, writeFile, readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
const dir = await mkdtemp(join(tmpdir(), "harness-pack-"));
const invoke = (cmd, args, cwd = dir) => execFileSync(cmd, args, { cwd, encoding: 'utf8', env: { ...process.env,  }, stdio: ['ignore','pipe','pipe'] });
const packed = process.argv[2] ? { filename: resolve(process.argv[2]) } : JSON.parse(invoke('npm', ['pack', '--json', '--pack-destination', dir], process.cwd()))[0];
const archive = resolve(dir, packed.filename);
const listing = invoke('tar', ['-tzf', archive]).trim().split('\n');
if (listing.some(p => !/^package\/(dist\/|README.md$|LICENSE$|package.json$)/.test(p))) throw new Error('Unexpected file in release archive');
if (!listing.includes('package/dist/cli.js') || !listing.includes('package/dist/web-dist/index.html')) throw new Error('Missing release resources');
await writeFile(join(dir, 'package.json'), JSON.stringify({ private: true, type: 'module' }));
invoke('npm', ['install', '--ignore-scripts', '--no-audit', '--no-fund', '--registry=https://registry.npmjs.org', archive]);
const prefix = join(dir, 'global');
invoke('npm', ['install', '--global', '--prefix', prefix, '--ignore-scripts', '--no-audit', '--no-fund', archive]);
const cli = join(prefix, 'bin/nekomimi');
if (!invoke(cli, ['--help']).includes('Nekomimi')) throw new Error('Missing CLI');
console.log(invoke(process.execPath, [new URL('./global-web-smoke.mjs', import.meta.url).pathname, cli, dir]).trim());
await writeFile(join(dir, 'smoke.mjs'), `import {Journal, exportSession, inspectBundle, importBundle} from 'nekomimi'; const j=await Journal.open('./session'); await j.append('fixture',{artifact:await j.artifact('offline pack fixture')}); await j.close(); await exportSession('./session',{format:'html',output:'./view.html'}); await exportSession('./session',{format:'bundle',output:'./bundle'}); await inspectBundle('./bundle'); await importBundle('./bundle','./imported');`);
invoke(process.execPath, ['smoke.mjs']);
JSON.parse(invoke(cli, ['replay', join(dir, 'imported')]));
await writeFile(join(dir, 'web-smoke.mjs'), await readFile(new URL('./pack-web-fixture.mjs', import.meta.url)));
invoke(process.execPath, ['web-smoke.mjs']);
console.log(JSON.stringify({ directory: dir, tarball: packed.filename, installed: true, cli: true, offlineExportImport: true, webStaticCommandExport: true }));
